<?php

use Illuminate\Database\Seeder;
use App\Attribute;

class AttributesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Attribute::create([
            'pet_id' => '1',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1'
        ]);
        Attribute::create([
            'pet_id' => '2',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '3',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '4',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '5',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '6',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '7',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '8',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '9',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '10',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '11',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '12',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '13',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '14',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
        Attribute::create([
            'pet_id' => '15',
            'friendly' => 'friendly',
            'good_with_kids' => 'good with Kids',
            'energetic' => 'energetic',
            'calm' => 'calm',
            'drools' => 'drools',
            'vocal' => 'vocal',
            'trained' => 'trained',
            'escape_artist' => 'escape artist',
            'novice_owner_ok' => 'novice owner ok',
            'aggressive_toward_humans' => 'timid with new people',
            'aggressive_toward_dogs' => 'dislikes dogs',
            'aggressive_toward_cats' => 'dislikes cats',
            'aggressive_toward_kids' => 'dislikes kids',
            'special_needs' => 'special needs',
            'shed_level' => '1',
        ]);
    }
}
